# Generated by Django 3.0.2 on 2020-01-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='images/none/none.jpg', upload_to='images/'),
        ),
    ]
