# Generated by Django 3.0.3 on 2020-03-06 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0004_task_doc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Task',
        ),
    ]
